// Operator dashboard i18n copy. Inline EN + ES per the project's existing
// "copy object per page" pattern (admin pages, schools page). Spanish is
// Claude-drafted — see TODO.md for the native-review queue.

export type OperatorLocale = 'en' | 'es';

export const operatorCopy = {
  en: {
    pageTitle: (campName: string) => `${campName} — Operator Dashboard`,
    welcome: (campName: string) => `Welcome, ${campName}`,
    listingQuality: 'Listing quality',
    listingQualityHelp:
      'Filled-in listings get more parent saves. Aim for 80% or higher.',
    sectionBasics: 'Basics',
    sectionContact: 'Contact + registration',
    sectionPricing: 'Pricing',
    sectionLogistics: 'Hours + extended care',
    sectionExtras: 'Extras',
    sectionPhotos: 'Photos',
    sectionCoverage: "When are you open?",
    coverageHelp:
      "Tell parents which Miami school holidays you're open. Updates here show up immediately on the parent-side closure pages.",
    fields: {
      description: 'Description',
      descriptionHelp: 'Plain text — no HTML. Aim for 2-3 sentences.',
      categories: 'Categories',
      ages_min: 'Minimum age',
      ages_max: 'Maximum age',
      phone: 'Phone',
      email: 'Email',
      website_url: 'Website',
      registration_url: 'Registration link',
      registration_deadline: 'Registration deadline',
      price_tier: 'Price tier',
      price_min_cents: 'Min price (USD)',
      price_max_cents: 'Max price (USD)',
      price_notes: 'Price notes',
      hours_start: 'Start time',
      hours_end: 'End time',
      before_care_offered: 'Before-care offered',
      before_care_start: 'Before-care start',
      before_care_price_cents: 'Before-care price (USD/week)',
      after_care_offered: 'After-care offered',
      after_care_end: 'After-care end',
      after_care_price_cents: 'After-care price (USD/week)',
      lunch_included: 'Lunch included',
      special_needs_friendly: 'Special-needs friendly',
      scholarships_available: 'Scholarships available',
      scholarships_notes: 'Scholarship details',
      accommodations: 'Special accommodations',
      photo_urls: 'Photo URLs (one per line, up to 5)',
    },
    save: 'Save changes',
    saving: 'Saving…',
    saved: 'Saved',
    error: 'Could not save — try again or refresh.',
    coverageLabels: {
      open: 'Open',
      closed: 'Closed',
      notes: 'Notes (optional)',
    },
    notFound: 'No camp found at that URL.',
  },
  es: {
    pageTitle: (campName: string) => `${campName} — Panel del Operador`,
    welcome: (campName: string) => `Bienvenido, ${campName}`,
    listingQuality: 'Calidad del listado',
    listingQualityHelp:
      'Los listados completos reciben más guardados de padres. Apunta a 80% o más.',
    sectionBasics: 'Básicos',
    sectionContact: 'Contacto e inscripción',
    sectionPricing: 'Precios',
    sectionLogistics: 'Horarios y cuidado extendido',
    sectionExtras: 'Extras',
    sectionPhotos: 'Fotos',
    sectionCoverage: '¿Cuándo estás abierto?',
    coverageHelp:
      'Diles a los padres cuáles feriados escolares de Miami estás abierto. Los cambios aquí aparecen al instante en las páginas de feriados.',
    fields: {
      description: 'Descripción',
      descriptionHelp: 'Texto plano — sin HTML. Apunta a 2-3 oraciones.',
      categories: 'Categorías',
      ages_min: 'Edad mínima',
      ages_max: 'Edad máxima',
      phone: 'Teléfono',
      email: 'Correo',
      website_url: 'Sitio web',
      registration_url: 'Enlace de inscripción',
      registration_deadline: 'Fecha límite de inscripción',
      price_tier: 'Nivel de precio',
      price_min_cents: 'Precio mínimo (USD)',
      price_max_cents: 'Precio máximo (USD)',
      price_notes: 'Notas de precio',
      hours_start: 'Hora de inicio',
      hours_end: 'Hora de fin',
      before_care_offered: 'Cuidado antes ofrecido',
      before_care_start: 'Inicio del cuidado antes',
      before_care_price_cents: 'Precio cuidado antes (USD/semana)',
      after_care_offered: 'Cuidado después ofrecido',
      after_care_end: 'Fin del cuidado después',
      after_care_price_cents: 'Precio cuidado después (USD/semana)',
      lunch_included: 'Almuerzo incluido',
      special_needs_friendly: 'Amigable con necesidades especiales',
      scholarships_available: 'Becas disponibles',
      scholarships_notes: 'Detalles de becas',
      accommodations: 'Adaptaciones especiales',
      photo_urls: 'URLs de fotos (una por línea, hasta 5)',
    },
    save: 'Guardar cambios',
    saving: 'Guardando…',
    saved: 'Guardado',
    error: 'No se pudo guardar — intenta de nuevo o recarga.',
    coverageLabels: {
      open: 'Abierto',
      closed: 'Cerrado',
      notes: 'Notas (opcional)',
    },
    notFound: 'No se encontró un campamento en esa URL.',
  },
} as const;
