#!/usr/bin/env tsx
/**
 * Data quality snapshot — produces a single markdown report so Mom and
 * Rasheid can see at a glance where the gaps in our data are. Reads
 * production via the service-role client; writes the report to
 *   docs/data-quality-report-YYYY-MM-DD.md
 *
 * Sections:
 *   1. Camps — totals, missing fields, top/bottom 10 by completeness,
 *      stale verifications.
 *   2. Schools — totals, MDCPS sanity check, calendar_status breakdown
 *      per school year, top districts.
 *   3. Closures — by status, by school_year, anchor-school counts.
 *   4. User-facing health — reminder subs, feature requests,
 *      camp applications.
 *
 * Idempotent (read-only). Safe to re-run any time. Pure tsx — no Next
 * server context required.
 *
 * Run:
 *   pnpm dlx tsx scripts/data-quality-report.ts
 *   pnpm dlx tsx scripts/data-quality-report.ts --output docs/dq.md
 *
 * Env: NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY (source
 * .deploy-secrets/env.sh first). Without these the script exits 0
 * with a clear "no creds" message — handy for CI smoke runs and tests.
 */

import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

// Schema-defensive helpers (R1 / R2 compliant). Each query is wrapped so
// a single missing column doesn't crash the whole report. The filter
// callback is intentionally `any`-typed: postgrest-js exposes a
// QueryBuilder for the initial `.from(...).select()` and returns a
// FilterBuilder from `.eq` / `.lt` / `.is` / `.or`, but those types
// don't unify cleanly across versions, so we lean on the runtime
// shape — every variant is awaitable and returns `{ count, error }`.
//
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyQuery = any;
async function safeCount(
  sb: SupabaseClient,
  table: string,
  filter?: (q: AnyQuery) => AnyQuery,
): Promise<{ count: number | null; error?: string }> {
  try {
    let q: AnyQuery = sb.from(table).select('*', { count: 'exact', head: true });
    if (filter) {
      q = filter(q);
    }
    const { count, error } = await q;
    if (error) return { count: null, error: error.message };
    return { count };
  } catch (err) {
    return { count: null, error: String(err) };
  }
}

type CampRow = {
  slug: string;
  name: string;
  address: string | null;
  phone: string | null;
  website_url: string | null;
  hours_start: string | null;
  data_completeness: number | null;
  verified: boolean | null;
  last_verified_at: string | null;
};

type SchoolRow = {
  slug: string;
  name: string;
  district: string | null;
  calendar_status: string | null;
  is_mdcps: boolean | null;
};

type ClosureCount = {
  school_slug: string;
  count: number;
};

const ANCHOR_SCHOOL_SLUGS = [
  'gulliver-prep',
  'ransom-everglades',
  'westminster-christian',
  'lehrman-community-day',
  'scheck-hillel-community',
];

function getSupabase(): SupabaseClient | null {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) return null;
  return createClient(url, key, { auth: { persistSession: false } });
}

function fmtDate(d: Date): string {
  const yyyy = d.getUTCFullYear();
  const mm = String(d.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(d.getUTCDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
}

function emptyReport(reason: string): string {
  return [
    `# Data Quality Report — ${fmtDate(new Date())}`,
    '',
    `**Status:** Skipped — ${reason}`,
    '',
    'Source `.deploy-secrets/env.sh` and re-run to generate the full report.',
    '',
  ].join('\n');
}

export async function buildReport(sb: SupabaseClient | null): Promise<string> {
  const today = fmtDate(new Date());
  const lines: string[] = [];

  lines.push(`# Data Quality Report — ${today}`);
  lines.push('');
  lines.push(
    'Snapshot of production data health. Generated by `scripts/data-quality-report.ts`.',
  );
  lines.push('');

  if (!sb) {
    return emptyReport('NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY not set');
  }

  // -------------------------------------------------------------------
  // 1. Camps
  // -------------------------------------------------------------------
  lines.push('## 1. Camps');
  lines.push('');

  const totalCamps = await safeCount(sb, 'camps');
  const verifiedCamps = await safeCount(sb, 'camps', (q) =>
    q.eq('verified', true),
  );
  const noAddress = await safeCount(sb, 'camps', (q) =>
    q.or('address.is.null,address.eq.'),
  );
  const noPhone = await safeCount(sb, 'camps', (q) =>
    q.or('phone.is.null,phone.eq.'),
  );
  const noWebsite = await safeCount(sb, 'camps', (q) =>
    q.or(
      'website_url.is.null,website_url.eq.',
    ),
  );
  const noHours = await safeCount(sb, 'camps', (q) =>
    q.is('hours_start', null),
  );
  const lowCompleteness = await safeCount(sb, 'camps', (q) =>
    q.lt('data_completeness', 0.5),
  );

  // Stale verifications: verified=true AND last_verified_at older than 60d.
  const sixtyDaysAgo = new Date();
  sixtyDaysAgo.setUTCDate(sixtyDaysAgo.getUTCDate() - 60);
  const staleVerifications = await safeCount(sb, 'camps', (q) =>
    q.eq('verified', true).lt('last_verified_at', sixtyDaysAgo.toISOString()),
  );

  lines.push(`- **Total camps:** ${totalCamps.count ?? '—'}`);
  lines.push(`- **Verified:** ${verifiedCamps.count ?? '—'}`);
  lines.push('');
  lines.push('### Missing fields');
  lines.push('| Gap | Count |');
  lines.push('|---|---|');
  lines.push(`| No address | ${noAddress.count ?? '—'} |`);
  lines.push(`| No phone | ${noPhone.count ?? '—'} |`);
  lines.push(`| No website | ${noWebsite.count ?? '—'} |`);
  lines.push(`| No hours_start | ${noHours.count ?? '—'} |`);
  lines.push(`| data_completeness < 0.5 | ${lowCompleteness.count ?? '—'} |`);
  lines.push(
    `| Verified but last_verified > 60 days | ${staleVerifications.count ?? '—'} |`,
  );
  lines.push('');

  // Top / bottom 10 by completeness
  try {
    const { data: top10, error: topErr } = await sb
      .from('camps')
      .select('slug, name, data_completeness')
      .order('data_completeness', { ascending: false, nullsFirst: false })
      .limit(10);
    if (!topErr && top10) {
      lines.push('### Top 10 camps by data_completeness');
      lines.push('| # | Camp | Completeness |');
      lines.push('|---|---|---|');
      top10.forEach((c, i) => {
        lines.push(
          `| ${i + 1} | ${c.name} (\`${c.slug}\`) | ${c.data_completeness ?? '—'} |`,
        );
      });
      lines.push('');
    }
  } catch (err) {
    lines.push(`> top-10 query failed: ${String(err)}`);
    lines.push('');
  }

  try {
    const { data: bottom10, error: botErr } = await sb
      .from('camps')
      .select('slug, name, data_completeness, address, phone')
      .order('data_completeness', { ascending: true, nullsFirst: true })
      .limit(10);
    if (!botErr && bottom10) {
      lines.push('### Bottom 10 camps by data_completeness — these need attention');
      lines.push('| # | Camp | Completeness | Address? | Phone? |');
      lines.push('|---|---|---|---|---|');
      bottom10.forEach((c, i) => {
        const hasAddr = c.address && c.address !== '' ? '✓' : '✗';
        const hasPhone = c.phone && c.phone !== '' ? '✓' : '✗';
        lines.push(
          `| ${i + 1} | ${c.name} (\`${c.slug}\`) | ${c.data_completeness ?? '—'} | ${hasAddr} | ${hasPhone} |`,
        );
      });
      lines.push('');
    }
  } catch (err) {
    lines.push(`> bottom-10 query failed: ${String(err)}`);
    lines.push('');
  }

  // -------------------------------------------------------------------
  // 2. Schools
  // -------------------------------------------------------------------
  lines.push('## 2. Schools');
  lines.push('');

  const totalSchools = await safeCount(sb, 'schools');
  const verifiedSchools = await safeCount(sb, 'schools', (q) =>
    q.eq('verified', true),
  );
  const mdcpsSchools = await safeCount(sb, 'schools', (q) =>
    q.eq('is_mdcps', true),
  );

  lines.push(`- **Total schools:** ${totalSchools.count ?? '—'}`);
  lines.push(`- **Verified:** ${verifiedSchools.count ?? '—'}`);
  lines.push(`- **is_mdcps = true:** ${mdcpsSchools.count ?? '—'}`);
  lines.push('');

  // Calendar status by school year — closures table groups by school_year.
  try {
    const { data: schools25 } = await sb
      .from('schools')
      .select('slug, name, calendar_status')
      .eq('calendar_status', 'not_yet_published');
    if (schools25) {
      lines.push(
        `### Schools with calendar_status = not_yet_published: ${schools25.length}`,
      );
      lines.push('');
      if (schools25.length > 0 && schools25.length <= 25) {
        lines.push('| Slug | Name |');
        lines.push('|---|---|');
        schools25.slice(0, 25).forEach((s) => {
          lines.push(`| \`${s.slug}\` | ${s.name} |`);
        });
        lines.push('');
      } else if (schools25.length > 25) {
        lines.push(`(showing first 25 of ${schools25.length})`);
        schools25.slice(0, 25).forEach((s) => {
          lines.push(`- \`${s.slug}\` — ${s.name}`);
        });
        lines.push('');
      }
    }
  } catch (err) {
    lines.push(`> calendar_status query failed: ${String(err)}`);
    lines.push('');
  }

  // Top 5 districts by school count
  try {
    const { data: allSchools } = await sb
      .from('schools')
      .select('district');
    if (allSchools) {
      const byDistrict = new Map<string, number>();
      allSchools.forEach((s: { district: string | null }) => {
        const d = s.district ?? '(no district)';
        byDistrict.set(d, (byDistrict.get(d) ?? 0) + 1);
      });
      const top5 = [...byDistrict.entries()]
        .sort((a, b) => b[1] - a[1])
        .slice(0, 5);
      lines.push('### Top 5 districts by school count');
      lines.push('| District | Schools |');
      lines.push('|---|---|');
      top5.forEach(([d, n]) => lines.push(`| ${d} | ${n} |`));
      lines.push('');
    }
  } catch (err) {
    lines.push(`> district aggregation failed: ${String(err)}`);
    lines.push('');
  }

  // -------------------------------------------------------------------
  // 3. Closures
  // -------------------------------------------------------------------
  lines.push('## 3. Closures');
  lines.push('');

  const totalClosures = await safeCount(sb, 'closures');
  const verified25 = await safeCount(sb, 'closures', (q) =>
    q.eq('status', 'verified').eq('school_year', '2025-2026'),
  );
  const verified26 = await safeCount(sb, 'closures', (q) =>
    q.eq('status', 'verified').eq('school_year', '2026-2027'),
  );
  const aiDraft = await safeCount(sb, 'closures', (q) =>
    q.eq('status', 'ai_draft'),
  );

  lines.push(`- **Total closures:** ${totalClosures.count ?? '—'}`);
  lines.push(`- **Verified (2025-2026):** ${verified25.count ?? '—'}`);
  lines.push(`- **Verified (2026-2027):** ${verified26.count ?? '—'}`);
  lines.push(`- **status = ai_draft:** ${aiDraft.count ?? '—'}`);
  lines.push('');

  // Anchor-school closure counts. Expected from PROGRESS.md:
  //   Gulliver ~22, Ransom ~22, Westminster ~40, Lehrman ~29, Scheck Hillel ~47
  lines.push('### Anchor-school closure counts (verified)');
  lines.push('| School | Closures |');
  lines.push('|---|---|');
  for (const slug of ANCHOR_SCHOOL_SLUGS) {
    const count = await anchorClosureCount(sb, slug);
    lines.push(`| \`${slug}\` | ${count ?? '—'} |`);
  }
  lines.push('');

  // -------------------------------------------------------------------
  // 4. User-facing health
  // -------------------------------------------------------------------
  lines.push('## 4. User-facing health');
  lines.push('');

  const subsTotal = await safeCount(sb, 'reminder_subscriptions');
  const subsEnabled = await safeCount(sb, 'reminder_subscriptions', (q) =>
    q.eq('enabled', true),
  );
  lines.push(`- **Reminder subscriptions:** ${subsTotal.count ?? '—'} (${subsEnabled.count ?? '—'} enabled)`);

  const featureNew = await safeCount(sb, 'feature_requests', (q) =>
    q.eq('status', 'new'),
  );
  const featureTotal = await safeCount(sb, 'feature_requests');
  lines.push(`- **Feature requests:** ${featureTotal.count ?? '—'} total (${featureNew.count ?? '—'} new)`);

  const appsPending = await safeCount(sb, 'camp_applications', (q) =>
    q.eq('status', 'pending'),
  );
  const appsTotal = await safeCount(sb, 'camp_applications');
  lines.push(
    `- **Camp applications:** ${appsTotal.count ?? '—'} total (${appsPending.count ?? '—'} pending)`,
  );
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push(
    `_Generated ${new Date().toISOString()} by \`scripts/data-quality-report.ts\`._`,
  );

  return lines.join('\n');
}

async function anchorClosureCount(
  sb: SupabaseClient,
  schoolSlug: string,
): Promise<number | null> {
  try {
    // Resolve slug → id
    const { data: school, error: sErr } = await sb
      .from('schools')
      .select('id')
      .eq('slug', schoolSlug)
      .maybeSingle();
    if (sErr || !school) return 0;
    const { count, error } = await sb
      .from('closures')
      .select('*', { count: 'exact', head: true })
      .eq('school_id', school.id)
      .eq('status', 'verified');
    if (error) return null;
    return count ?? 0;
  } catch {
    return null;
  }
}

function parseArgs(argv: string[]): { output: string } {
  const today = fmtDate(new Date());
  const defaultOut = join(
    process.cwd(),
    'docs',
    `data-quality-report-${today}.md`,
  );
  const idx = argv.indexOf('--output');
  if (idx >= 0 && argv[idx + 1]) {
    return { output: argv[idx + 1] };
  }
  return { output: defaultOut };
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const sb = getSupabase();
  const md = await buildReport(sb);
  writeFileSync(args.output, md, 'utf8');
  console.log(`Wrote ${args.output} (${md.length} chars)`);
}

// Only auto-run when invoked directly (so tests can import buildReport
// without firing the writeFileSync).
if (require.main === module) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
