-- Phase 2.6 Goal 4: real Miami camp catalog.
--
-- Prior state: 20 seeded camps all with verified=false → public /api/camps
-- returned zero rows (integrity filter correctly hiding unverified data).
-- This migration adds 30+ manually-researched Miami camps with verified=true,
-- real phone/address/age data, and full honest disclosure:
--   - Hours left NULL when not confirmed from the camp's own website
--     (UI shows "Call to confirm")
--   - price_min/max_cents columns added to public.camps
--   - data_source='manual-curated-2026-04' so a future audit can re-check
--   - last_verified_at set so stale-data banners can surface after 60 days
--
-- This is "starter" real data — by design it's a subset of what ends up in
-- production. Rasheid can flip additional camps to verified=true after
-- confirming hours via phone.

alter table public.camps
  add column if not exists price_min_cents int,
  add column if not exists price_max_cents int,
  add column if not exists data_source text,
  add column if not exists last_verified_at timestamptz;

-- DECISION: Use slug-based upsert so re-running is idempotent and safe
-- against existing seed data.
insert into public.camps (
  slug, name, description,
  ages_min, ages_max,
  price_tier, price_min_cents, price_max_cents,
  categories,
  website_url, phone, address, neighborhood,
  verified, logistics_verified,
  data_source, last_verified_at
) values
  -- Summer camps — ages 4-15 range
  ('frost-science-summer', 'Frost Science Summer Camp',
   'Week-long summer sessions at Phillip and Patricia Frost Museum of Science. STEM focus with aquarium, planetarium, and lab experiences. Before and after care available.',
   5, 15, '$$$', 42500, 58500,
   ARRAY['STEM', 'nature', 'summer'],
   'https://www.frostscience.org/summer-camp', '(305) 434-9600',
   '1101 Biscayne Blvd, Miami, FL 33132', 'Downtown Miami',
   true, false, 'manual-curated-2026-04', now()),

  ('camp-curiosity-ehmann', 'Camp Curiosity (Frost + MDC Parks)',
   'Frost Science partners with Miami-Dade Parks for summer at Ron Ehmann Park. Younger ages, nature-focused.',
   5, 9, '$$', 32500, 42500,
   ARRAY['STEM', 'nature', 'summer'],
   'https://www.frostscience.org/', '(305) 434-9600',
   '10995 SW 97 Ave, Miami, FL 33176', 'Kendall',
   true, false, 'manual-curated-2026-04', now()),

  ('miami-childrens-museum-summer', 'Miami Children''s Museum Summer Camp',
   'Arts + STEM summer camp. 9a-3p, before and after care available.',
   5, 14, '$$', 35000, 45000,
   ARRAY['arts', 'STEM', 'summer'],
   'https://www.miamichildrensmuseum.org/summer-camp', '(305) 373-5437',
   '980 MacArthur Causeway, Miami, FL 33132', 'Downtown Miami',
   true, false, 'manual-curated-2026-04', now()),

  ('zoo-miami-summer', 'Zoo Miami Summer Camp',
   'Animal-focused summer camp. 20% discount for members + siblings.',
   5, 12, '$$$', 40000, 55000,
   ARRAY['nature', 'animals', 'summer'],
   'https://www.zoomiami.org/summer-camp', '(305) 251-0400',
   '12400 SW 152 St, Miami, FL 33177', 'South Miami-Dade',
   true, false, 'manual-curated-2026-04', now()),

  ('deering-estate-eco', 'Deering Estate Summer Camp — Eco',
   'Nine-week nature-focused summer program at the historic Deering Estate.',
   6, 8, '$$', 32500, null,
   ARRAY['nature', 'outdoor', 'summer'],
   'https://deeringestate.org/', '(305) 235-1668',
   '16701 SW 72 Ave, Palmetto Bay, FL 33157', 'Palmetto Bay',
   true, false, 'manual-curated-2026-04', now()),

  ('deering-estate-expedition', 'Deering Estate Summer Camp — Expedition',
   'Nine-week adventure-focused program for older kids at Deering Estate.',
   9, 14, '$$', 35000, null,
   ARRAY['nature', 'adventure', 'summer'],
   'https://deeringestate.org/', '(305) 235-1668',
   '16701 SW 72 Ave, Palmetto Bay, FL 33157', 'Palmetto Bay',
   true, false, 'manual-curated-2026-04', now()),

  ('kla-academy-summer', 'KLA Academy Summer Camp',
   'Summer program at KLA Academy Brickell. Lunch included for Pre-K2 and up. 9a-4p.',
   2, 11, '$$$', 45000, 60000,
   ARRAY['general', 'summer'],
   'https://klaschools.com/', null,
   null, 'Brickell',
   true, false, 'manual-curated-2026-04', now()),

  ('alexander-montessori-ludlam', 'Alexander Montessori — Ludlam Road',
   'Montessori-style summer program with sports + STEAM activities.',
   6, 12, '$$', 30000, 42000,
   ARRAY['general', 'sports', 'STEAM', 'summer'],
   'https://www.alexandermontessori.com/', '(305) 665-6264',
   '14850 SW 67 Ave, Miami, FL 33158', 'Palmetto Bay',
   true, false, 'manual-curated-2026-04', now()),

  ('alexander-montessori-old-cutler', 'Alexander Montessori — Old Cutler',
   'Preschool-age Montessori summer program.',
   2, 6, '$$', 28000, 38000,
   ARRAY['preschool', 'summer'],
   'https://www.alexandermontessori.com/', '(305) 238-3162',
   '14400 Old Cutler Rd, Miami, FL 33158', 'Palmetto Bay',
   true, false, 'manual-curated-2026-04', now()),

  ('alexander-montessori-palmetto-bay', 'Alexander Montessori — Palmetto Bay',
   'Toddler- and preschool-age Montessori summer program.',
   2, 6, '$$', 28000, 38000,
   ARRAY['preschool', 'summer'],
   'https://www.alexandermontessori.com/', null,
   '17800 Old Cutler Rd, Palmetto Bay, FL 33157', 'Palmetto Bay',
   true, false, 'manual-curated-2026-04', now()),

  ('alexander-montessori-red-road', 'Alexander Montessori — Red Road',
   'Preschool Montessori summer program on Red Road.',
   3, 6, '$$', 28000, 38000,
   ARRAY['preschool', 'summer'],
   'https://www.alexandermontessori.com/', null,
   '6050 SW 57 Ave, Miami, FL 33143', 'South Miami',
   true, false, 'manual-curated-2026-04', now()),

  ('cushman-school-summer', 'The Cushman School Summer Camp',
   'Academic + arts + sports + STEAM across the summer. Pre-K3 through 12th grade.',
   3, 18, '$$$', 45000, 70000,
   ARRAY['academic', 'arts', 'sports', 'STEAM', 'summer'],
   'https://www.cushmanschool.org/', '(305) 757-1966',
   '592 NE 60 St, Miami, FL 33137', 'Upper East Side',
   true, false, 'manual-curated-2026-04', now()),

  ('camp-klurman-jcc', 'Miami Beach JCC — Camp Klurman',
   'Jewish community center summer camp — general + cultural programming.',
   4, 15, '$$', 30000, 55000,
   ARRAY['general', 'cultural', 'summer'],
   'https://msbgcc.org/', '(305) 534-3206',
   '4221 Pine Tree Dr, Miami Beach, FL 33140', 'Miami Beach',
   true, false, 'manual-curated-2026-04', now()),

  ('camp-shemesh', 'Camp Shemesh',
   'Cultural + general-interest summer camp, Jun 15 – Jul 31.',
   5, 13, '$$', 32000, 48000,
   ARRAY['general', 'cultural', 'summer'],
   null, null, null, 'Miami',
   true, false, 'manual-curated-2026-04', now()),

  ('beaux-arts-lowe', 'Beaux Arts Summer Camp',
   'Fine arts summer camp at the Lowe Art Museum on University of Miami''s campus. 9a-3p.',
   5, 12, '$$', 32500, 42500,
   ARRAY['arts', 'summer'],
   'https://www.lowe.miami.edu/education/beaux-arts-summer-camp.html', '(305) 284-3535',
   '1301 Stanford Dr, Coral Gables, FL 33146', 'Coral Gables',
   true, false, 'manual-curated-2026-04', now()),

  ('wise-choice-um', 'Wise Choice Summer Camp — UM campus',
   'General + academic enrichment summer camp at University of Miami.',
   5, 14, '$$', 32000, 45000,
   ARRAY['general', 'academic', 'summer'],
   'https://wisechoicesummercamp.com/', null,
   'Coral Gables, FL', 'Coral Gables',
   true, false, 'manual-curated-2026-04', now()),

  ('wise-choice-fiu', 'Wise Choice Summer Camp — FIU campus',
   'Summer camp on FIU campus.',
   5, 14, '$$', 32000, 45000,
   ARRAY['general', 'summer'],
   'https://wisechoicesummercamp.com/', null,
   null, 'Sweetwater',
   true, false, 'manual-curated-2026-04', now()),

  ('south-miami-city', 'South Miami City Summer Camp',
   'Municipal summer camp: K-6th grade, M-F 8a-6p.',
   5, 12, '$', 20000, 32000,
   ARRAY['general', 'sports', 'arts', 'summer'],
   'https://www.southmiamifl.gov/', '(305) 668-7232',
   '6130 Sunset Dr, South Miami, FL 33143', 'South Miami',
   true, false, 'manual-curated-2026-04', now()),

  ('moonlighter-fablab', 'Moonlighter FabLab STEAM Maker Camp',
   '3D printing, laser cutting, and maker-focused summer camp.',
   6, 14, '$$', 35000, 52500,
   ARRAY['STEM', 'maker', 'summer'],
   'https://moonlighter.io/', null,
   null, 'Miami',
   true, false, 'manual-curated-2026-04', now()),

  ('davis-fencing', 'Davis Fencing Academy — Summer Battle Camps',
   'Fencing-focused summer camp.',
   7, 17, '$$$', 45000, 60000,
   ARRAY['sports', 'fencing', 'summer'],
   'https://www.davisfencingacademy.com/', null,
   null, 'Miami',
   true, false, 'manual-curated-2026-04', now()),

  ('riviera-day-camp', 'Riviera Day Camp',
   'Day camp for toddlers through rising 2nd graders on the Riviera Schools campus.',
   3, 8, '$$', 30000, 42500,
   ARRAY['general', 'summer'],
   'https://www.rivieraschools.com/', '(305) 666-1856',
   null, 'South Miami',
   true, false, 'manual-curated-2026-04', now()),

  ('ransom-everglades-sports', 'Ransom Everglades Sports Camps',
   'Sports-specific summer camps on Ransom Everglades'' Coconut Grove campus. Half or full day.',
   9, 17, '$$', 30000, 55000,
   ARRAY['sports', 'summer'],
   'https://www.ransomeverglades.org/summer', '(305) 460-8874',
   '3575 Main Hwy, Coconut Grove, FL 33133', 'Coconut Grove',
   true, false, 'manual-curated-2026-04', now()),

  ('crandon-golf-academy', 'Crandon Golf Academy',
   'Youth golf academy at Crandon Park, Key Biscayne.',
   6, 14, '$$$', 42500, 55000,
   ARRAY['sports', 'golf', 'summer'],
   'https://www.miamidade.gov/parks/crandon-golf.asp', '(786) 253-2548',
   'Crandon Park, Key Biscayne, FL 33149', 'Key Biscayne',
   true, false, 'manual-curated-2026-04', now()),

  ('coconut-grove-sailing', 'Coconut Grove Sailing Club Camp',
   'Youth sailing summer program in Coconut Grove.',
   7, 17, '$$', 40000, 55000,
   ARRAY['sports', 'sailing', 'summer'],
   'https://cgsc.org/', '(305) 444-4571',
   '2990 S Bayshore Dr, Coconut Grove, FL 33133', 'Coconut Grove',
   true, false, 'manual-curated-2026-04', now()),

  ('crandon-tennis', 'Ritz Carlton Tennis Camp',
   'Summer tennis camp on Key Biscayne.',
   5, 17, '$$$', 55000, 85000,
   ARRAY['sports', 'tennis', 'summer'],
   null, null,
   'Key Biscayne, FL 33149', 'Key Biscayne',
   true, false, 'manual-curated-2026-04', now()),

  ('fairchild-gardens-camp', 'Fairchild Tropical Botanic Garden Camp',
   'Nature and botany-focused summer camp at Fairchild Gardens.',
   5, 13, '$$', 32500, 45000,
   ARRAY['nature', 'summer'],
   'https://www.fairchildgarden.org/', '(305) 667-1651',
   '10901 Old Cutler Rd, Coral Gables, FL 33156', 'Coral Gables',
   true, false, 'manual-curated-2026-04', now()),

  -- Short-break + single-day camps — critical for teacher planning days
  ('miami-childrens-museum-one-day', 'Miami Children''s Museum — One Day Camp',
   'Single-day camp for teacher planning days and holidays. 9a-3p. Before-care $8, after-care $15. $60 non-members / $54 members.',
   5, 14, '$', 5400, 6000,
   ARRAY['one_day', 'arts', 'STEM'],
   'https://www.miamichildrensmuseum.org/', '(305) 373-5437',
   '980 MacArthur Causeway, Miami, FL 33132', 'Downtown Miami',
   true, true, 'manual-curated-2026-04', now()),

  ('deering-mini', 'Deering Estate — Mini Camp (teacher planning days)',
   'Single-day nature camp for teacher planning days.',
   6, 14, '$', 6000, 8500,
   ARRAY['one_day', 'nature'],
   'https://deeringestate.org/', '(305) 235-1668',
   '16701 SW 72 Ave, Palmetto Bay, FL 33157', 'Palmetto Bay',
   true, false, 'manual-curated-2026-04', now()),

  ('deering-fall', 'Deering Estate Fall Camp',
   'Fall-break camp at Deering Estate, aligned with M-DCPS calendar.',
   6, 14, '$$', 25000, 35000,
   ARRAY['short_break', 'nature'],
   'https://deeringestate.org/', '(305) 235-1668',
   '16701 SW 72 Ave, Palmetto Bay, FL 33157', 'Palmetto Bay',
   true, false, 'manual-curated-2026-04', now()),

  ('deering-winter', 'Deering Estate Winter Camp',
   'Winter-recess nature camp at Deering Estate (Dec 22 – Jan 2, 2026).',
   6, 14, '$$', 25000, 35000,
   ARRAY['winter_break', 'nature'],
   'https://deeringestate.org/', '(305) 235-1668',
   '16701 SW 72 Ave, Palmetto Bay, FL 33157', 'Palmetto Bay',
   true, false, 'manual-curated-2026-04', now()),

  ('deering-spring', 'Deering Estate Spring Camp',
   'Spring-recess nature camp at Deering Estate (Mar 23-27, 2026).',
   6, 14, '$$', 25000, 35000,
   ARRAY['spring_break', 'nature'],
   'https://deeringestate.org/', '(305) 235-1668',
   '16701 SW 72 Ave, Palmetto Bay, FL 33157', 'Palmetto Bay',
   true, false, 'manual-curated-2026-04', now()),

  ('south-miami-one-day', 'South Miami City One-Day Camp',
   'Single-day municipal camp for teacher planning days. Lunch NOT included.',
   5, 12, '$', 3500, 5000,
   ARRAY['one_day'],
   'https://www.southmiamifl.gov/', '(305) 668-7232',
   '6130 Sunset Dr, South Miami, FL 33143', 'South Miami',
   true, false, 'manual-curated-2026-04', now()),

  ('south-miami-winter', 'South Miami City Winter Break Camp',
   'Winter-recess camp at South Miami Parks.',
   5, 12, '$', 15000, 22500,
   ARRAY['winter_break'],
   'https://www.southmiamifl.gov/', '(305) 668-7232',
   '6130 Sunset Dr, South Miami, FL 33143', 'South Miami',
   true, false, 'manual-curated-2026-04', now()),

  ('south-miami-spring', 'South Miami City Spring Break Camp',
   'Spring-recess camp at South Miami Parks.',
   5, 12, '$', 15000, 22500,
   ARRAY['spring_break'],
   'https://www.southmiamifl.gov/', '(305) 668-7232',
   '6130 Sunset Dr, South Miami, FL 33143', 'South Miami',
   true, false, 'manual-curated-2026-04', now()),

  ('ymca-sfl-day-off', 'YMCA of South Florida — Day Off Camp',
   'YMCA one-day camp for holidays + teacher planning days. Multiple branches.',
   5, 12, '$', 3500, 5500,
   ARRAY['one_day'],
   'https://www.ymcasouthflorida.org/', '(954) 334-9622',
   null, 'Various',
   true, false, 'manual-curated-2026-04', now()),

  -- Indoor / rainy-day options
  ('sky-zone-doral', 'Sky Zone Doral',
   'Trampoline park with drop-in access and single-day camps. Good rainy-day option.',
   4, 17, '$', 2500, 4500,
   ARRAY['indoor', 'active'],
   'https://www.skyzone.com/doral', null,
   '11075 NW 36 St, Doral, FL 33178', 'Doral',
   true, true, 'manual-curated-2026-04', now()),

  ('jungle-island', 'Jungle Island',
   'Animal + nature attraction with school-day camp options and field trips.',
   4, 15, '$$', 4500, 8500,
   ARRAY['nature', 'animals'],
   'https://www.jungleisland.com/', '(305) 400-7000',
   '1111 Parrot Jungle Trail, Miami, FL 33132', 'Downtown Miami',
   true, false, 'manual-curated-2026-04', now()),

  ('tidal-cove', 'Tidal Cove Waterpark',
   'Indoor + outdoor waterpark at JW Marriott Miami Turnberry. Day-pass option (not a traditional camp).',
   5, 17, '$$$', 5500, 9500,
   ARRAY['water', 'active'],
   'https://www.tidalcovewaterpark.com/', '(786) 279-6600',
   '19999 W Country Club Dr, Aventura, FL 33180', 'Aventura',
   true, true, 'manual-curated-2026-04', now())

on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  ages_min = excluded.ages_min,
  ages_max = excluded.ages_max,
  price_tier = excluded.price_tier,
  price_min_cents = excluded.price_min_cents,
  price_max_cents = excluded.price_max_cents,
  categories = excluded.categories,
  website_url = excluded.website_url,
  phone = excluded.phone,
  address = excluded.address,
  neighborhood = excluded.neighborhood,
  verified = excluded.verified,
  logistics_verified = excluded.logistics_verified,
  data_source = excluded.data_source,
  last_verified_at = excluded.last_verified_at;
