-- Phase 3.0 — anchor private school calendar import (2025-26 + 2026-27).
-- Generated by scripts/parse-school-calendars.ts on 2026-04-25.
--
-- Sources (per row): docs/plans/calendar-pdfs/<file> + sidecar JSON when present.
-- Verification doc: docs/plans/calendar-import-verification-2026-04-25.md
-- Parsed JSON:      docs/plans/parsed-school-calendars-2026-04-25.json
--
-- DO NOT APPLY until Noah reviews the verification doc and approves.
-- Rerunning is safe: ON CONFLICT DO NOTHING against the new unique index.

-- 1. Unique index on (school_id, start_date, name) — required for the
--    ON CONFLICT clause below. CONCURRENTLY would be safer in prod but
--    Supabase migrations don't run in transactions for that, and the
--    closures table is small.
create unique index if not exists closures_school_start_name_unique
  on public.closures (school_id, start_date, name);

do $$
declare
  gulliver_preparatory_school_id uuid;
  lehrman_community_day_school_id uuid;
  ransom_everglades_school_id uuid;
  scheck_hillel_community_school_id uuid;
  westminster_christian_school_id uuid;
begin
  select id into gulliver_preparatory_school_id from public.schools where slug = 'gulliver-preparatory-school';
  if gulliver_preparatory_school_id is null then raise exception 'school slug gulliver-preparatory-school not found — fix schools table first'; end if;
  -- Insert Lehrman Community Day School if missing (was not in 316-school import).
  insert into public.schools (slug, name, district, city, state, type, is_mdcps, religious_affiliation, address, phone, website, data_source)
    values ('lehrman-community-day-school', 'Lehrman Community Day School', 'Miami-Dade Private', 'Miami Beach', 'FL', 'private', false, 'Jewish', '727 77th Street, Miami Beach, FL 33141', '(305) 866-2771', 'https://www.lehrmanschool.org', 'calendar-import-2026-04-25')
    on conflict (slug) do nothing;
  select id into lehrman_community_day_school_id from public.schools where slug = 'lehrman-community-day-school';
  if lehrman_community_day_school_id is null then raise exception 'school slug lehrman-community-day-school not found — fix schools table first'; end if;
  select id into ransom_everglades_school_id from public.schools where slug = 'ransom-everglades-school';
  if ransom_everglades_school_id is null then raise exception 'school slug ransom-everglades-school not found — fix schools table first'; end if;
  -- Insert Scheck Hillel Community School if missing (was not in 316-school import).
  insert into public.schools (slug, name, district, city, state, type, is_mdcps, religious_affiliation, address, phone, website, data_source)
    values ('scheck-hillel-community-school', 'Scheck Hillel Community School', 'Miami-Dade Private', 'North Miami Beach', 'FL', 'private', false, 'Jewish', '19000 NE 25th Avenue, North Miami Beach, FL 33180', '(305) 931-2831', 'https://www.eHillel.org', 'calendar-import-2026-04-25')
    on conflict (slug) do nothing;
  select id into scheck_hillel_community_school_id from public.schools where slug = 'scheck-hillel-community-school';
  if scheck_hillel_community_school_id is null then raise exception 'school slug scheck-hillel-community-school not found — fix schools table first'; end if;
  select id into westminster_christian_school_id from public.schools where slug = 'westminster-christian-school';
  if westminster_christian_school_id is null then raise exception 'school slug westminster-christian-school not found — fix schools table first'; end if;

  -- Gulliver Preparatory School (gulliver-preparatory-school)
  insert into public.closures (
    school_id, name, start_date, end_date, status, source, source_url, source_type,
    school_year, category, closed_for_students, is_early_release, confidence
  ) values
    (gulliver_preparatory_school_id, 'Grade 9 Orientation', '2025-08-10', '2025-08-11', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'orientation', false, false, 'high'),
    (gulliver_preparatory_school_id, 'Middle School & Upper School Orientation Days', '2025-08-10', '2025-08-12', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'orientation', false, false, 'high'),
    (gulliver_preparatory_school_id, 'Primary & Lower School Meet & Greet', '2025-08-13', '2025-08-13', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'orientation', false, false, 'high'),
    (gulliver_preparatory_school_id, 'First Day of School', '2025-08-14', '2025-08-14', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'first_day', false, false, 'high'),
    (gulliver_preparatory_school_id, 'Labor Day Holiday', '2025-09-01', '2025-09-01', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Rosh Hashanah Holiday', '2025-09-23', '2025-09-23', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'religious_holiday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Yom Kippur Holiday', '2025-10-02', '2025-10-02', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'religious_holiday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Teacher Workday – No Classes (PS/LS Parent Conferences)', '2025-10-17', '2025-10-17', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'teacher_workday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Teacher Professional Development Day – No Classes', '2025-11-03', '2025-11-03', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'teacher_workday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Thanksgiving Recess', '2025-11-24', '2025-11-28', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'break', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Early Dismissal (Half day)', '2025-12-19', '2025-12-19', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'other', false, true, 'high'),
    (gulliver_preparatory_school_id, 'Winter Recess', '2025-12-22', '2026-01-02', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'break', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Classes Resume', '2026-01-05', '2026-01-05', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'other', false, false, 'high'),
    (gulliver_preparatory_school_id, 'Martin Luther King, Jr. Holiday', '2026-01-19', '2026-01-19', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Presidents'' Day Recess', '2026-02-16', '2026-02-20', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'No Classes for Primary & Lower School Students (PS/LS Parent Conferences)', '2026-03-18', '2026-03-18', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'parent_conference', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Spring Recess', '2026-03-30', '2026-04-03', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'break', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Teacher Professional Development Day – No Classes', '2026-04-06', '2026-04-06', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'teacher_workday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Class of 2026 Graduation (tentative)', '2026-05-21', '2026-05-21', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'graduation', false, false, 'medium'),
    (gulliver_preparatory_school_id, 'Last Day of School, Gr PK-SK – Early Dismissal', '2026-05-21', '2026-05-21', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'last_day', false, true, 'high'),
    (gulliver_preparatory_school_id, 'Last Day of School, Gr 1-11 – Early Dismissal', '2026-05-22', '2026-05-22', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'last_day', false, true, 'high'),
    (gulliver_preparatory_school_id, 'Memorial Day Holiday', '2026-05-25', '2026-05-25', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Teacher Workday – No Classes', '2026-05-26', '2026-05-29', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2025-2026', 'teacher_workday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Independence Day Observed-School Closed', '2026-07-03', '2026-07-03', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'federal_holiday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'New Staff Orientation', '2026-08-06', '2026-08-07', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'orientation', true, false, 'high'),
    (gulliver_preparatory_school_id, 'MS & US Orientation Days', '2026-08-17', '2026-08-18', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'orientation', true, false, 'high'),
    (gulliver_preparatory_school_id, 'First Day of Classes', '2026-08-20', '2026-08-20', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'first_day', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Labor Day-No School', '2026-09-07', '2026-09-07', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'federal_holiday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Rosh Hashanah', '2026-09-12', '2026-09-12', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'religious_holiday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Yom Kippur-No School', '2026-09-21', '2026-09-21', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'religious_holiday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Faculty Workday; PS/LS Parent Conferences', '2026-10-23', '2026-10-23', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'teacher_workday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Schoolwide PD Day-No School for Students', '2026-11-02', '2026-11-02', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'other', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Thanksgiving Break-School Closed', '2026-11-23', '2026-11-27', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'break', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Early Dismissal', '2026-12-18', '2026-12-18', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'other', false, true, 'high'),
    (gulliver_preparatory_school_id, 'Winter Break- School Closed', '2026-12-21', '2027-01-01', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'break', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Martin Luther King Day-School Closed', '2027-01-18', '2027-01-18', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'federal_holiday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Spring Break-School Closed', '2027-03-22', '2027-03-26', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'break', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Easter Sunday', '2027-03-28', '2027-03-28', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'religious_holiday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Faculty Workday-No School for Students', '2027-03-29', '2027-03-29', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'teacher_workday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'PS/LS Parent Conferences-No School for Students', '2027-04-07', '2027-04-07', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'parent_conference', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Passover', '2027-04-21', '2027-04-29', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'religious_holiday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Schoolwide PD Day-No School for Students', '2027-04-30', '2027-04-30', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'other', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Class of 2027 Graduation', '2027-05-20', '2027-05-20', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'graduation', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Last Day of School/End of Quarter Four (43 days)', '2027-05-28', '2027-05-28', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'last_day', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Memorial Day-School Closed', '2027-05-31', '2027-05-31', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'federal_holiday', true, false, 'high'),
    (gulliver_preparatory_school_id, 'Juneteenth Observed-School Closed', '2027-06-18', '2027-06-18', 'verified', 'official_pdf', 'https://www.gulliverprep.org/wp-content/uploads/academic_calendar.pdf', 'school_pdf', '2026-2027', 'federal_holiday', true, false, 'high')
  on conflict (school_id, start_date, name) do nothing;

  -- Lehrman Community Day School (lehrman-community-day-school)
  insert into public.closures (
    school_id, name, start_date, end_date, status, source, source_url, source_type,
    school_year, category, closed_for_students, is_early_release, confidence
  ) values
    (lehrman_community_day_school_id, 'Orientation', '2025-08-18', '2025-08-18', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'orientation', false, false, 'medium'),
    (lehrman_community_day_school_id, 'First Day of School', '2025-08-19', '2025-08-19', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'first_day', false, false, 'high'),
    (lehrman_community_day_school_id, 'Labor Day', '2025-09-01', '2025-09-01', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'federal_holiday', true, false, 'high'),
    (lehrman_community_day_school_id, '1 PM Dismissal', '2025-09-12', '2025-09-12', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'other', false, true, 'medium'),
    (lehrman_community_day_school_id, '1 PM Dismissal', '2025-09-22', '2025-09-22', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'other', false, true, 'medium'),
    (lehrman_community_day_school_id, 'Rosh Hashanah', '2025-09-23', '2025-09-24', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'religious_holiday', true, false, 'high'),
    (lehrman_community_day_school_id, 'Yom Kippur', '2025-10-01', '2025-10-02', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'religious_holiday', true, false, 'high'),
    (lehrman_community_day_school_id, 'Early Dismissal', '2025-10-06', '2025-10-06', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'other', false, true, 'medium'),
    (lehrman_community_day_school_id, 'Sukkot', '2025-10-07', '2025-10-08', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'religious_holiday', true, false, 'high'),
    (lehrman_community_day_school_id, 'Simchat Torah / Shemini Atzeret', '2025-10-13', '2025-10-15', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'religious_holiday', true, false, 'medium'),
    (lehrman_community_day_school_id, 'Thanksgiving Break', '2025-11-26', '2025-11-28', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'break', true, false, 'high'),
    (lehrman_community_day_school_id, 'Parent/Teacher Conferences', '2025-12-08', '2025-12-08', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'parent_conference', true, false, 'medium'),
    (lehrman_community_day_school_id, '1 PM Dismissal', '2025-12-14', '2025-12-14', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'other', false, true, 'medium'),
    (lehrman_community_day_school_id, 'Winter Break', '2025-12-24', '2026-01-06', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'break', true, false, 'high'),
    (lehrman_community_day_school_id, 'School Resumes', '2026-01-07', '2026-01-07', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'other', false, false, 'medium'),
    (lehrman_community_day_school_id, '1 PM Dismissal', '2026-01-12', '2026-01-14', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'other', false, true, 'medium'),
    (lehrman_community_day_school_id, 'Martin Luther King Jr. Day', '2026-01-19', '2026-01-19', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'federal_holiday', true, false, 'high'),
    (lehrman_community_day_school_id, 'February Break', '2026-02-16', '2026-02-17', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'break', true, false, 'high'),
    (lehrman_community_day_school_id, 'Early Dismissal', '2026-03-03', '2026-03-03', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'other', false, true, 'medium'),
    (lehrman_community_day_school_id, 'Professional Development Day', '2026-03-30', '2026-03-30', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'teacher_workday', true, false, 'high'),
    (lehrman_community_day_school_id, 'Passover Break', '2026-03-31', '2026-04-10', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'religious_holiday', true, false, 'high'),
    (lehrman_community_day_school_id, 'School Resumes', '2026-04-13', '2026-04-13', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'other', false, false, 'medium'),
    (lehrman_community_day_school_id, 'Yom HaShoah', '2026-04-14', '2026-04-14', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'religious_holiday', false, false, 'medium'),
    (lehrman_community_day_school_id, 'Yom HaZikaron', '2026-04-21', '2026-04-21', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'religious_holiday', false, false, 'medium'),
    (lehrman_community_day_school_id, 'Yom Ha''Atzmaut', '2026-04-22', '2026-04-22', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'religious_holiday', false, false, 'medium'),
    (lehrman_community_day_school_id, '1 PM Dismissal', '2026-05-21', '2026-05-21', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'other', false, true, 'medium'),
    (lehrman_community_day_school_id, 'Classes End', '2026-05-22', '2026-05-22', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'last_day', false, false, 'medium'),
    (lehrman_community_day_school_id, 'Memorial Day', '2026-05-25', '2026-05-25', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'federal_holiday', true, false, 'high'),
    (lehrman_community_day_school_id, 'Last Day of School (Early Dismissal)', '2026-06-09', '2026-06-09', 'verified', 'official_pdf', 'https://www.lehrmanschool.org/parents/2025-26-calendar.cfm', 'school_website_calendar_page', '2025-2026', 'last_day', false, true, 'medium')
  on conflict (school_id, start_date, name) do nothing;

  -- Ransom Everglades School (ransom-everglades-school)
  insert into public.closures (
    school_id, name, start_date, end_date, status, source, source_url, source_type,
    school_year, category, closed_for_students, is_early_release, confidence
  ) values
    (ransom_everglades_school_id, 'Faculty Orientation', '2025-08-06', '2025-08-12', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'teacher_workday', true, false, 'medium'),
    (ransom_everglades_school_id, 'Orientation – 6th, 9th, and new students', '2025-08-19', '2025-08-19', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'orientation', false, false, 'high'),
    (ransom_everglades_school_id, 'First Day of School for Students', '2025-08-20', '2025-08-20', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'first_day', false, false, 'high'),
    (ransom_everglades_school_id, 'Labor Day – School Closed', '2025-09-01', '2025-09-01', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high'),
    (ransom_everglades_school_id, 'Rosh Hashanah – School Closed', '2025-09-23', '2025-09-23', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'religious_holiday', true, false, 'high'),
    (ransom_everglades_school_id, 'Yom Kippur – School Closed', '2025-10-02', '2025-10-02', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'religious_holiday', true, false, 'high'),
    (ransom_everglades_school_id, 'Parent Conferences – No Classes', '2025-10-17', '2025-10-17', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'parent_conference', true, false, 'high'),
    (ransom_everglades_school_id, 'Parent Conferences – No Classes', '2025-10-20', '2025-10-20', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'parent_conference', true, false, 'high'),
    (ransom_everglades_school_id, 'Thanksgiving Break', '2025-11-24', '2025-11-28', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'break', true, false, 'high'),
    (ransom_everglades_school_id, 'Last Day of 1st Semester', '2025-12-19', '2025-12-19', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'other', false, false, 'high'),
    (ransom_everglades_school_id, 'Holiday Break', '2025-12-22', '2026-01-02', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'break', true, false, 'high'),
    (ransom_everglades_school_id, 'Classes Resume – First Day of 2nd Semester', '2026-01-05', '2026-01-05', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'other', false, false, 'high'),
    (ransom_everglades_school_id, 'Martin Luther King Jr. National Day of Service – No Classes', '2026-01-19', '2026-01-19', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high'),
    (ransom_everglades_school_id, 'Winter Break (Presidents'' Week)', '2026-02-13', '2026-02-20', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'break', true, false, 'high'),
    (ransom_everglades_school_id, 'Spring Break', '2026-03-30', '2026-04-03', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'break', true, false, 'high'),
    (ransom_everglades_school_id, 'Passover', '2026-04-02', '2026-04-02', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'religious_holiday', true, false, 'high'),
    (ransom_everglades_school_id, 'Good Friday', '2026-04-03', '2026-04-03', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'religious_holiday', true, false, 'high'),
    (ransom_everglades_school_id, 'Commencement', '2026-05-22', '2026-05-22', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'graduation', false, false, 'high'),
    (ransom_everglades_school_id, 'Memorial Day – School Closed', '2026-05-25', '2026-05-25', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high'),
    (ransom_everglades_school_id, 'Last Day of 2nd Semester', '2026-06-02', '2026-06-02', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'last_day', false, false, 'high'),
    (ransom_everglades_school_id, 'Juneteenth – School Closed', '2026-06-19', '2026-06-19', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high'),
    (ransom_everglades_school_id, 'Independence Day Observed – School Closed', '2026-07-03', '2026-07-03', 'verified', 'official_pdf', 'https://www.ransomeverglades.org/news-and-events/calendar', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high')
  on conflict (school_id, start_date, name) do nothing;

  -- Scheck Hillel Community School (scheck-hillel-community-school)
  insert into public.closures (
    school_id, name, start_date, end_date, status, source, source_url, source_type,
    school_year, category, closed_for_students, is_early_release, confidence
  ) values
    (scheck_hillel_community_school_id, 'Tentative Orientation Days', '2025-08-14', '2025-08-15', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'orientation', false, false, 'medium'),
    (scheck_hillel_community_school_id, 'First Day of School', '2025-08-18', '2025-08-18', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'first_day', false, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Labor Day', '2025-09-01', '2025-09-01', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Rosh Hashanah', '2025-09-22', '2025-09-24', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'religious_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Yom Kippur', '2025-10-01', '2025-10-03', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'religious_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Sukkot', '2025-10-06', '2025-10-08', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'religious_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Shemini Atzeret & Simchat Torah', '2025-10-13', '2025-10-15', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'religious_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'No Classes - Parent/Teacher Conferences', '2025-11-24', '2025-11-25', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'parent_conference', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Thanksgiving Break', '2025-11-26', '2025-11-28', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'break', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Winter Break', '2025-12-22', '2026-01-02', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'break', true, false, 'high'),
    (scheck_hillel_community_school_id, 'No Classes - Professional Development', '2026-01-05', '2026-01-05', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'teacher_workday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Martin Luther King, Jr. Day', '2026-01-19', '2026-01-19', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Presidents'' Day', '2026-02-16', '2026-02-16', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, '2 PM Dismissal - Ta''anit Esther', '2026-03-02', '2026-03-02', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'religious_holiday', false, true, 'high'),
    (scheck_hillel_community_school_id, '12 PM Dismissal - Purim', '2026-03-03', '2026-03-03', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'religious_holiday', false, true, 'high'),
    (scheck_hillel_community_school_id, 'No Classes - Parent/Teacher Conferences', '2026-03-16', '2026-03-16', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'parent_conference', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Passover Break', '2026-03-30', '2026-04-10', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'religious_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, '2 PM Dismissal: Commencement', '2026-05-20', '2026-05-20', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'graduation', false, true, 'high'),
    (scheck_hillel_community_school_id, '12 PM Dismissal: Erev Shavuot', '2026-05-21', '2026-05-21', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'religious_holiday', false, true, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Shavuot', '2026-05-22', '2026-05-22', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'religious_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Memorial Day', '2026-05-25', '2026-05-25', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, '12 PM Dismissal - Last Day of School', '2026-06-11', '2026-06-11', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'last_day', false, true, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Juneteenth', '2026-06-19', '2026-06-19', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'First Day of School', '2026-08-19', '2026-08-19', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'first_day', false, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Labor Day', '2026-09-07', '2026-09-07', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'federal_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Erev Rosh Hashanah', '2026-09-11', '2026-09-11', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'religious_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Yom Kippur', '2026-09-21', '2026-09-21', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'religious_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, '10 AM Late Start', '2026-09-22', '2026-09-22', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'other', false, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Erev Sukkot', '2026-09-25', '2026-09-25', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'religious_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Sukkot', '2026-09-28', '2026-09-28', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'religious_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Erev Shemini Atzeret & Simchat Torah', '2026-10-02', '2026-10-02', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'religious_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'No Classes - Parent/Teacher Conferences', '2026-11-23', '2026-11-24', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'parent_conference', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Thanksgiving Break', '2026-11-25', '2026-11-27', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'break', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Winter Break', '2026-12-21', '2027-01-01', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'break', true, false, 'high'),
    (scheck_hillel_community_school_id, 'No Classes - Professional Development', '2027-01-04', '2027-01-04', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'teacher_workday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Martin Luther King, Jr. Day', '2027-01-18', '2027-01-18', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'federal_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Presidents'' Day', '2027-02-15', '2027-02-15', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'federal_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'No Classes - Parent/Teacher Conferences', '2027-03-11', '2027-03-11', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'parent_conference', true, false, 'high'),
    (scheck_hillel_community_school_id, '12 PM Dismissal - Ta''anit Esther', '2027-03-22', '2027-03-22', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'religious_holiday', false, true, 'high'),
    (scheck_hillel_community_school_id, '12 PM Dismissal - Purim', '2027-03-23', '2027-03-23', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'religious_holiday', false, true, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Passover Break', '2027-04-19', '2027-04-30', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'religious_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Tentative: Commencement', '2027-05-23', '2027-05-23', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'graduation', false, false, 'medium'),
    (scheck_hillel_community_school_id, 'Tentative: Commencement - 2 PM Dismissal', '2027-05-26', '2027-05-26', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'graduation', false, true, 'medium'),
    (scheck_hillel_community_school_id, 'Campus Closed - Memorial Day', '2027-05-31', '2027-05-31', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'federal_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, '12 PM Dismissal - Last Day of School', '2027-06-03', '2027-06-03', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'last_day', false, true, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Erev Shavuot & Shavuot', '2027-06-10', '2027-06-12', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'religious_holiday', true, false, 'high'),
    (scheck_hillel_community_school_id, 'Campus Closed - Juneteenth', '2027-06-18', '2027-06-18', 'verified', 'official_pdf', 'https://www.ehillel.org/quicklinks/calendar', 'school_pdf', '2026-2027', 'federal_holiday', true, false, 'high')
  on conflict (school_id, start_date, name) do nothing;

  -- Westminster Christian School (westminster-christian-school)
  insert into public.closures (
    school_id, name, start_date, end_date, status, source, source_url, source_type,
    school_year, category, closed_for_students, is_early_release, confidence
  ) values
    (westminster_christian_school_id, 'Preschool Preview Day', '2025-08-08', '2025-08-08', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'orientation', false, false, 'high'),
    (westminster_christian_school_id, 'First Day of School (ES/MS) – 11:30 a.m. dismissal', '2025-08-11', '2025-08-11', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'first_day', false, true, 'high'),
    (westminster_christian_school_id, 'First Day on Campus (HS)', '2025-08-18', '2025-08-18', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'first_day', false, false, 'high'),
    (westminster_christian_school_id, 'No School: Labor Day', '2025-09-01', '2025-09-01', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high'),
    (westminster_christian_school_id, 'No School: Faculty In-Service Day', '2025-10-10', '2025-10-10', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'teacher_workday', true, false, 'high'),
    (westminster_christian_school_id, 'Early Dismissal: 11:30 a.m.', '2025-11-21', '2025-11-21', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'other', false, true, 'high'),
    (westminster_christian_school_id, 'No School: Thanksgiving Break', '2025-11-24', '2025-11-28', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'break', true, false, 'high'),
    (westminster_christian_school_id, 'Early Dismissal: 11:30 a.m.', '2025-12-19', '2025-12-19', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'other', false, true, 'high'),
    (westminster_christian_school_id, 'No School: Christmas Break', '2025-12-22', '2026-01-05', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'break', true, false, 'high'),
    (westminster_christian_school_id, 'No School: Martin Luther King, Jr. Day', '2026-01-19', '2026-01-19', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'federal_holiday', true, false, 'high'),
    (westminster_christian_school_id, 'No School: Faculty In-Service Day', '2026-02-13', '2026-02-13', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'teacher_workday', true, false, 'high'),
    (westminster_christian_school_id, 'No School: Winter Break', '2026-02-16', '2026-02-17', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'break', true, false, 'high'),
    (westminster_christian_school_id, 'No School: Faculty In-Service Day', '2026-03-13', '2026-03-13', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'teacher_workday', true, false, 'high'),
    (westminster_christian_school_id, 'No School: Spring Break', '2026-03-23', '2026-03-27', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'break', true, false, 'high'),
    (westminster_christian_school_id, 'No School: Easter Break', '2026-04-03', '2026-04-06', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'religious_holiday', true, false, 'high'),
    (westminster_christian_school_id, '12th Grade: Last Day of School', '2026-05-01', '2026-05-01', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'last_day', false, false, 'high'),
    (westminster_christian_school_id, '8th Grade: Last Day of School', '2026-05-18', '2026-05-18', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'last_day', false, false, 'high'),
    (westminster_christian_school_id, '5th Grade: Last Day of School', '2026-05-20', '2026-05-20', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'last_day', false, false, 'high'),
    (westminster_christian_school_id, 'Last Day of School: 11:30 a.m. Dismissal', '2026-05-21', '2026-05-21', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'last_day', false, true, 'high'),
    (westminster_christian_school_id, 'No School: Faculty In-Service Day', '2026-05-22', '2026-05-22', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2025-2026', 'teacher_workday', true, false, 'high'),
    (westminster_christian_school_id, 'Preschool Preview Day', '2026-08-07', '2026-08-07', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'orientation', false, false, 'high'),
    (westminster_christian_school_id, 'First Day of School: Early Dismissal', '2026-08-10', '2026-08-10', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'first_day', false, true, 'high'),
    (westminster_christian_school_id, 'First Day on Campus (HS)', '2026-08-17', '2026-08-17', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'first_day', false, false, 'high'),
    (westminster_christian_school_id, 'No School: Labor Day', '2026-09-07', '2026-09-07', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'federal_holiday', true, false, 'high'),
    (westminster_christian_school_id, 'No School: Faculty In-Service Day', '2026-10-09', '2026-10-09', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'teacher_workday', true, false, 'high'),
    (westminster_christian_school_id, 'No School: Veterans Day', '2026-11-11', '2026-11-11', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'federal_holiday', true, false, 'high'),
    (westminster_christian_school_id, 'Early Dismissal', '2026-11-20', '2026-11-20', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'other', false, true, 'high'),
    (westminster_christian_school_id, 'No School: Thanksgiving Break', '2026-11-23', '2026-11-27', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'break', true, false, 'high'),
    (westminster_christian_school_id, 'Early Dismissal', '2026-12-18', '2026-12-18', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'other', false, true, 'high'),
    (westminster_christian_school_id, 'No School: Christmas Break', '2026-12-21', '2027-01-04', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'break', true, false, 'high'),
    (westminster_christian_school_id, 'No School: Martin Luther King, Jr. Day', '2027-01-18', '2027-01-18', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'federal_holiday', true, false, 'high'),
    (westminster_christian_school_id, 'No School: Faculty In-Service Day', '2027-02-12', '2027-02-12', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'teacher_workday', true, false, 'high'),
    (westminster_christian_school_id, 'No School: Winter Break', '2027-02-15', '2027-02-16', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'break', true, false, 'high'),
    (westminster_christian_school_id, 'No School: Faculty In-Service Day', '2027-03-12', '2027-03-12', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'teacher_workday', true, false, 'high'),
    (westminster_christian_school_id, 'No School: Spring Break', '2027-03-22', '2027-03-29', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'break', true, false, 'high'),
    (westminster_christian_school_id, 'Grade 12: Last Day of School', '2027-05-07', '2027-05-07', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'last_day', false, false, 'high'),
    (westminster_christian_school_id, 'Grade 8: Last Day of School', '2027-05-17', '2027-05-17', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'last_day', false, false, 'high'),
    (westminster_christian_school_id, 'Grade 5: Last Day of School', '2027-05-19', '2027-05-19', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'last_day', false, false, 'high'),
    (westminster_christian_school_id, 'Last Day of School: Early Dismissal', '2027-05-20', '2027-05-20', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'last_day', false, true, 'high'),
    (westminster_christian_school_id, 'No School: Faculty In-Service Day', '2027-05-21', '2027-05-21', 'verified', 'official_pdf', 'https://www.wcsmiami.org/news-and-events/key-dates-2025-26', 'school_pdf', '2026-2027', 'teacher_workday', true, false, 'high')
  on conflict (school_id, start_date, name) do nothing;

  -- Promote calendar_status only where the imported data is trustworthy.
  update public.schools set calendar_status = 'verified_multi_year', last_synced_at = now() where slug = 'gulliver-preparatory-school';
  update public.schools set calendar_status = 'verified_current', last_synced_at = now() where slug = 'ransom-everglades-school';
  update public.schools set calendar_status = 'verified_multi_year', last_synced_at = now() where slug = 'scheck-hillel-community-school';
  update public.schools set calendar_status = 'verified_multi_year', last_synced_at = now() where slug = 'westminster-christian-school';

end $$;
